# Force bare `claude` to use the Anthropic endpoint by default.
claude() {
  ANTHROPIC_BASE_URL="https://api.anthropic.com" command claude "$@"
}

alias zc='ANTHROPIC_BASE_URL="${Z_AI_BASE_URL}" ANTHROPIC_API_KEY="${Z_AI_AUTH_TOKEN}" ANTHROPIC_DEFAULT_HAIKU_MODEL="glm-4.5-air" ANTHROPIC_DEFAULT_SONNET_MODEL="glm-4.6" ANTHROPIC_DEFAULT_OPUS_MODEL="glm-4.6" command claude'
alias dc='ANTHROPIC_BASE_URL="${DEEPSEEK_BASE_URL}" ANTHROPIC_API_KEY="${DEEPSEEK_AUTH_TOKEN}" ANTHROPIC_TIMEOUT_MS="${DEEPSEEK_API_TIMEOUT_MS}" ANTHROPIC_MODEL="${DEEPSEEK_MODEL}" ANTHROPIC_SMALL_FAST_MODEL="${DEEPSEEK_SMALL_FAST_MODEL}" CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="${DEEPSEEK_CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC}" command claude'
